#!/usr/bin/env node

const yargs = require('yargs/yargs');
const { hideBin } = require('yargs/helpers');
const credentials = require('./lib/credentials');
const appwrite = require('./lib/appwrite');
const defaults = require('./lib/defaults');

credentials.loadCredentials();
defaults.loadDefaults();

const argv = yargs(hideBin(process.argv))
    .command('connect', 'Connect to Appwrite', (yargs) => {
        return yargs
            .option('endpoint', {
                describe: 'Appwrite endpoint',
                type: 'string',
                default: 'https://cloud.appwrite.io/v1',
            })
            .option('project', {
                describe: 'Appwrite project ID',
                type: 'string',
                demandOption: true,
            })
            .option('apikey', {
                describe: 'Appwrite API key',
                type: 'string',
                demandOption: true,
            });
    }, (argv) => {
        credentials.saveCredentials(argv.endpoint, argv.project, argv.apikey);
    })
    .command('create-project', 'Create a new project', (yargs) => {
        return yargs
            .option('endpoint', {
                describe: 'Project endpoint',
                type: 'string',
                demandOption: true,
            })
            .option('project', {
                describe: 'Project ID',
                type: 'string',
                demandOption: true,
            })
            .option('apikey', {
                describe: 'API key',
                type: 'string',
                demandOption: true,
            });
    }, (argv) => {
        // TODO: Implement create-project command
    })
    // TODO: Add more commands here
    .help()
    .argv;

