#!/usr/bin/env node

const credentials = require('./lib/credentials');
const appwrite = require('./lib/appwrite');
const defaults = require('./lib/defaults');
const { yargs } = require('./lib/commands')

credentials.loadCredentials();
defaults.loadDefaults();

const argv = yargs(process.argv)
    .addConnectCommand()
    .addProjectsCommand()
    .help()
    .argv;

